// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw_knPzhMfsBCVe5WAi7pvbfH3mA_Fk9E',
    appId: '1:520257539326:web:3824c5c9bad9e5879269af',
    messagingSenderId: '520257539326',
    projectId: 'fir-405b9',
    authDomain: 'fir-405b9.firebaseapp.com',
    storageBucket: 'fir-405b9.firebasestorage.app',
    measurementId: 'G-H16T0X8EWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1p3FCMoHAkWwQBtz_I_XLL4Fgv5w5UUA',
    appId: '1:520257539326:android:c8caf81becd731e89269af',
    messagingSenderId: '520257539326',
    projectId: 'fir-405b9',
    storageBucket: 'fir-405b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC36arbpTeIQc8bGKxFVAw56D_QrwhqWD4',
    appId: '1:520257539326:ios:306cc5ed0cb2fa799269af',
    messagingSenderId: '520257539326',
    projectId: 'fir-405b9',
    storageBucket: 'fir-405b9.firebasestorage.app',
    iosBundleId: 'com.example.amazon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC36arbpTeIQc8bGKxFVAw56D_QrwhqWD4',
    appId: '1:520257539326:ios:306cc5ed0cb2fa799269af',
    messagingSenderId: '520257539326',
    projectId: 'fir-405b9',
    storageBucket: 'fir-405b9.firebasestorage.app',
    iosBundleId: 'com.example.amazon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw_knPzhMfsBCVe5WAi7pvbfH3mA_Fk9E',
    appId: '1:520257539326:web:394035ff6f13cfc89269af',
    messagingSenderId: '520257539326',
    projectId: 'fir-405b9',
    authDomain: 'fir-405b9.firebaseapp.com',
    storageBucket: 'fir-405b9.firebasestorage.app',
    measurementId: 'G-W3B6K5EVD1',
  );
}
